// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "LandingPage": {
    "title": "PDF Invoice Generator",
    "subtitle": "Generate professional invoices instantly",
    "description": "Our PDF Invoice Generator helps you create, manage, and send professional invoices in seconds. Save time and get paid faster with automated invoice creation.",
    "features": {
      "title": "Features",
      "items": [
        {
          "title": "Professional Templates",
          "description": "Choose from a variety of professionally designed templates"
        },
        {
          "title": "Quick Generation",
          "description": "Create invoices in seconds with our intuitive interface"
        },
        {
          "title": "Cloud Storage",
          "description": "Access your invoices anywhere, anytime"
        },
        {
          "title": "Automated Calculations",
          "description": "Automatic tax and total calculations"
        }
      ]
    },
    "cta": "Start Creating Invoices",
    "subscribe": {
      "title": "Stay Updated",
      "description": "Subscribe to our newsletter for the latest features and updates",
      "placeholder": "Enter your email",
      "button": "Subscribe",
      "success": "Thank you for subscribing!",
      "error": "Something went wrong. Please try again."
    }
  },
  "Navigation": {
    "home": "Home",
    "features": "Features",
    "pricing": "Pricing",
    "app": "Go to App",
    "language": "Language"
  },
  "Footer": {
    "copyright": "© PDF Invoice Generator. All rights reserved.",
    "links": {
      "privacy": "Privacy Policy",
      "terms": "Terms of Service",
      "contact": "Contact Us"
    }
  },
  "Metadata": {
    "about": {
      "title": "Invoice PDF Generator with Live Preview | No Sign-Up",
      "description": "Create and download professional PDF invoices instantly with real-time preview. Free and open-source. No signup required.",
      "keywords": "invoice tool, free invoice generator, PDF invoices, invoice creator, billing software"
    }
  }
};
export default messages;