import dayjs from "dayjs";
import {
  AlertCircleIcon,
  FileTextIcon,
  LinkIcon,
  PencilIcon,
} from "lucide-react";
import dynamic from "next/dynamic";
import Link from "next/link";
import type { Dispatch, SetStateAction } from "react";

import {
  type InvoiceData,
  type MobileTabsValues,
  DEFAULT_MOBILE_TAB,
  MOBILE_TABS_VALUES,
} from "@/app/schema";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { CustomTooltip } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";

import { getAppMetadata, updateAppMetadata } from "../utils/get-app-metadata";
import { InvoiceForm } from "./invoice-form";
import { InvoicePDFDownloadLink } from "./invoice-pdf-download-link";
import { MobileFormScrollContainer } from "./mobile-form-scroll-container";

const DesktopPDFViewerModuleLoading = () => {
  return (
    <div className="flex h-[580px] w-full items-center justify-center border border-gray-200 bg-gray-200 lg:h-[620px] 2xl:h-[700px]">
      <div className="text-center">
        <div className="mx-auto mb-4 h-8 w-8 animate-spin rounded-full border-4 border-blue-500 border-t-transparent" />
        <p className="text-gray-600">Loading PDF viewer...</p>
      </div>
    </div>
  );
};

const MobileInvoicePDFViewerModuleLoading = () => {
  return (
    <div className="flex h-[520px] w-[650px] items-center justify-center border border-gray-200 bg-gray-200 lg:h-[620px] 2xl:h-[700px]">
      <div className="text-center">
        <div className="mx-auto mb-4 h-8 w-8 animate-spin rounded-full border-4 border-blue-500 border-t-transparent" />
        <p className="text-gray-600">Loading PDF viewer...</p>
      </div>
    </div>
  );
};

const DesktopInvoicePDFViewer = dynamic(
  () => {
    return import("./invoice-pdf-preview/desktop-pdf-viewer").then((mod) => {
      return mod.DesktopInvoicePDFViewer;
    });
  },

  {
    ssr: false,
    loading: () => {
      return <DesktopPDFViewerModuleLoading />;
    },
  },
);

const MobileInvoicePDFViewer = dynamic(
  () => {
    return import("./invoice-pdf-preview/mobile-pdf-viewer").then((mod) => {
      return mod.MobileInvoicePDFViewer;
    });
  },
  {
    ssr: false,
    loading: () => {
      return <MobileInvoicePDFViewerModuleLoading />;
    },
  },
);

const PdfViewer = ({ isMobile }: { isMobile: boolean }) => {
  // Both viewers read the single PDF generated by `InvoicePdfInstanceProvider`.
  //
  // Use Mobile PDF viewer for:
  // 1. Mobile devices
  // 2. Any in-app browser/WebView environment (new logic for platforms like X.com, LinkedIn, etc.)
  // This is due to limitations of the standard PDF viewer in these environments
  // https://github.com/diegomura/react-pdf/issues/714
  if (isMobile) {
    return <MobileInvoicePDFViewer />;
  }

  // Normal version for standard desktop browsers
  return <DesktopInvoicePDFViewer />;
};

const TAB_INVOICE_FORM = MOBILE_TABS_VALUES[0];
const TAB_INVOICE_PREVIEW = MOBILE_TABS_VALUES[1];

function LocalStorageNotice() {
  return (
    <CustomTooltip
      trigger={
        <button
          type="button"
          className="cursor-default text-zinc-700 transition-colors hover:text-zinc-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2"
        >
          Saved locally in your browser
        </button>
      }
      content="No data is uploaded to the server"
      side="bottom"
      popoverOnMobile
      className="w-fit"
    />
  );
}

export function InvoiceClientPage({
  invoiceDataState,
  handleInvoiceDataChange,
  handleShareInvoice,
  isMobile,
  canShareInvoice,
  setInvoiceFormHasErrors,
}: {
  invoiceDataState: InvoiceData;
  handleInvoiceDataChange: (invoiceData: InvoiceData) => void;
  handleShareInvoice: () => void;
  isMobile: boolean;
  canShareInvoice: boolean;
  setInvoiceFormHasErrors: Dispatch<SetStateAction<boolean>>;
}) {
  const appMetadata = getAppMetadata();

  const invoiceLastUpdatedAtFormatted = appMetadata?.invoiceLastUpdatedAt
    ? dayjs(appMetadata.invoiceLastUpdatedAt)
        .locale("en")
        .format("MMM D, YYYY [at] HH:mm")
    : null;

  const defaultMobileTab =
    appMetadata?.lastVisitedMobileTab || DEFAULT_MOBILE_TAB;

  return (
    <>
      {isMobile ? (
        <div>
          <Tabs
            defaultValue={defaultMobileTab}
            className="w-full"
            onValueChange={(value) => {
              const newValue = value as MobileTabsValues;

              // update the last visited mobile tab in the app metadata
              updateAppMetadata((current) => {
                return {
                  ...current,
                  lastVisitedMobileTab: newValue,
                };
              });
            }}
          >
            <TabsList className="w-full">
              <TabsTrigger value={TAB_INVOICE_FORM} className="flex-1">
                <span className="flex items-center gap-1">
                  <PencilIcon className="h-4 w-4" />
                  Edit Invoice
                </span>
              </TabsTrigger>
              <TabsTrigger value={TAB_INVOICE_PREVIEW} className="flex-1">
                <span className="flex items-center gap-1">
                  <FileTextIcon className="h-4 w-4" />
                  Preview PDF
                </span>
              </TabsTrigger>
            </TabsList>
            <TabsContent value={TAB_INVOICE_FORM} className="mt-1">
              <MobileFormScrollContainer className="h-[520px] overflow-auto rounded-lg border-b px-3 shadow-sm">
                <InvoiceForm
                  invoiceData={invoiceDataState}
                  handleInvoiceDataChange={handleInvoiceDataChange}
                  isMobile
                  setInvoiceFormHasErrors={setInvoiceFormHasErrors}
                />
              </MobileFormScrollContainer>
            </TabsContent>
            <TabsContent value={TAB_INVOICE_PREVIEW} className="mt-1">
              <div className="flex h-[520px] w-full items-center justify-center">
                <PdfViewer isMobile={isMobile} />
              </div>
            </TabsContent>
          </Tabs>
          <div className="sticky bottom-0 z-50 mt-2 flex flex-col items-center justify-center gap-3 rounded-lg border border-t border-gray-200 bg-white px-3 py-3 shadow-[0_-4px_6px_-1px_rgba(0,0,0,0.1),0_-2px_4px_-2px_rgba(0,0,0,0.05)]">
            <CustomTooltip
              className={cn(!canShareInvoice && "bg-red-50")}
              trigger={
                <Button
                  data-disabled={!canShareInvoice} // for better UX than 'disabled'
                  onClick={handleShareInvoice}
                  variant="outline"
                  className={cn("mx-2 w-full")}
                >
                  <LinkIcon className="mr-1.5 size-4" />
                  Get link
                </Button>
              }
              content={
                canShareInvoice ? (
                  <div className="flex items-center gap-3 p-2">
                    <div className="space-y-1">
                      <p className="text-sm font-semibold text-slate-900">
                        Share Invoice Online
                      </p>
                      <p className="text-pretty text-xs leading-relaxed text-slate-700">
                        Generate a link to share this invoice with your clients.
                        They can view and download it directly from their
                        browser.
                      </p>
                    </div>
                  </div>
                ) : (
                  <div
                    data-testid="share-invoice-tooltip-content"
                    className="flex items-center gap-3 bg-red-50 p-3"
                  >
                    <AlertCircleIcon className="h-5 w-5 flex-shrink-0 fill-red-600 text-white" />
                    <div className="space-y-1">
                      <p className="text-sm font-semibold text-red-800">
                        Unable to Share Invoice
                      </p>
                      <p className="text-pretty text-xs leading-relaxed text-red-700">
                        Invoices with logos cannot be shared. Please remove the
                        logo to generate a shareable link. You can still
                        download the invoice as PDF and share it.
                      </p>
                    </div>
                  </div>
                )
              }
            />
            <InvoicePDFDownloadLink
              invoiceData={invoiceDataState}
              isMobile={isMobile}
            />
          </div>
          {/** Mobile version */}
          <div className="relative mx-2 mt-2 flex flex-wrap items-center justify-center gap-x-2 gap-y-1 text-center text-xs text-zinc-700 duration-500 animate-in fade-in slide-in-from-bottom-2">
            <LocalStorageNotice />
            {invoiceLastUpdatedAtFormatted ? (
              <>
                <span
                  className="hidden h-3 w-px bg-zinc-400 min-[453px]:block"
                  aria-hidden="true"
                />
                <span>
                  <span className="font-semibold">Invoice last updated:</span>{" "}
                  {invoiceLastUpdatedAtFormatted}
                </span>
              </>
            ) : null}
          </div>

          <div
            className="mt-5 flex flex-wrap justify-center gap-1 text-xs text-zinc-900"
            data-testid="mobile-terms-of-service-link"
          >
            By using this tool, you agree to the{" "}
            <Link href="/tos" className="underline hover:text-black">
              Terms of Service
            </Link>
          </div>
          {/* Founders info section (Mobile version) */}
          <div className="mt-5 flex w-full justify-center">
            <div className="flex items-center gap-1.5 text-xs text-zinc-700 duration-500 animate-in fade-in slide-in-from-bottom-2">
              <a href={"/founder"}>
                <img
                  src="https://ik.imagekit.io/fl2lbswwo/avatar.jpeg?updatedAt=1757456439459"
                  alt="Vlad Sazonau"
                  className="size-6 rounded-full"
                  height="24"
                  width="24"
                  loading="lazy"
                  decoding="async"
                />
              </a>
              <span>
                Made by{" "}
                <a href={"/founder"} className="underline hover:text-black">
                  Vlad Sazonau
                </a>
              </span>
            </div>
          </div>
        </div>
      ) : (
        // Desktop View
        <>
          {/* Invoice form section i.e. left column (Desktop version) */}
          <div className="col-span-4">
            <div className="h-[620px] overflow-auto border-b px-3 pl-0 shadow-[0_4px_6px_-4px_rgba(0,0,0,0.1)] 2xl:h-[700px]">
              <InvoiceForm
                invoiceData={invoiceDataState}
                handleInvoiceDataChange={handleInvoiceDataChange}
                setInvoiceFormHasErrors={setInvoiceFormHasErrors}
              />
            </div>

            {/* Founders info section (Desktop version) */}
            <div className="mt-1 flex items-center gap-1.5 text-xs text-zinc-800 duration-500 animate-in fade-in slide-in-from-bottom-2">
              <a href={"/founder"}>
                <img
                  src="https://ik.imagekit.io/fl2lbswwo/avatar.jpeg?updatedAt=1757456439459"
                  alt="Vlad Sazonau"
                  className="size-6 rounded-full"
                  height="24"
                  width="24"
                  loading="lazy"
                  decoding="async"
                />
              </a>
              <span>
                Made by{" "}
                <a href={"/founder"} className="underline hover:text-black">
                  Vlad Sazonau
                </a>
              </span>
            </div>
          </div>
          {/* Invoice preview section i.e. right column (Desktop version) */}
          <div className="relative col-span-8 h-[620px] w-full max-w-full 2xl:h-[700px]">
            <div className="relative">
              <div className="absolute -top-5 right-0 z-10 flex items-center gap-x-2 text-center text-xs text-zinc-700 duration-500 animate-in fade-in slide-in-from-bottom-2 md:-mb-5 lg:text-right">
                <LocalStorageNotice />
                {invoiceLastUpdatedAtFormatted ? (
                  <>
                    <span
                      className="hidden h-3 w-px bg-zinc-400 sm:block"
                      aria-hidden="true"
                    />
                    <span>
                      <span className="font-semibold">
                        Invoice last updated:
                      </span>{" "}
                      {invoiceLastUpdatedAtFormatted}
                    </span>
                  </>
                ) : null}
              </div>
            </div>
            <PdfViewer isMobile={false} />
            <div
              className="absolute -bottom-6 right-0 text-right text-xs text-zinc-800"
              data-testid="desktop-terms-of-service-link"
            >
              By using this tool, you agree to the{" "}
              <Link href="/tos" className="underline hover:text-black">
                Terms of Service
              </Link>
            </div>
          </div>
        </>
      )}
    </>
  );
}
