name: Notify on Playwright E2E Tests Failure

on:
  workflow_run:
    workflows: ["🎭 Playwright E2E tests"]
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify via GitHub issue (tag yourself)
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const issueTitle = `[CI] E2E workflow failed - ${new Date().toISOString()}`
            const issueBody = [
              '🎭 Playwright E2E tests',
              '',
              `- Repo: ${context.repo.owner}/${context.repo.repo}`,
              `- Workflow: ${context.payload.workflow_run.name}`,
              `- Status: ${context.payload.workflow_run.conclusion}`,
              `- URL: ${context.payload.workflow_run.html_url}`,
              '',
              '@VladSez'
            ].join('\n')
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
            })
